version: 1.4.{build}

image: Visual Studio 2017

configuration: Release

platform: x86

build:
  project: ForexTester-BetterVolume-1.4.sln
  verbosity: minimal

artifacts:
- path: Release\ForexTester-BetterVolume-1.4.dll
  name: ForexTester-BetterVolume-1.4.dll
